name: Feature Branch CI

on:
  push:
    branches:
    - 'feature/**'

jobs:
  ci:
    name: Run ktlint
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run ktlint
      run: bash ./gradlew ktlintCheck --stacktrace
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
