name: iOS Beta Deployment

on:
  push:
    branches:
    - "feature/**" # TODO: Replace with release branch name

defaults:
  run:
    shell: bash

env:
  IS_CI: true
    
jobs:
  deployment:
    runs-on: macos-latest
    environment: ios_production
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Homebrew install git-crypt
      run: brew install git-crypt
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: true
    - name: git-crypt unlock secrets
      run: |
        echo "$GIT_CRYPT_KEY" | base64 --decode > git-crypt.key
        git-crypt unlock git-crypt.key
        rm git-crypt.key
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.118.0
      with:
        ruby-version: '2.6.5'
        bundler-cache: true
        working-directory: './iosHyperskillApp'
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '11'
        distribution: 'corretto'
    #- name: Generate build konfig
    #  run: ./gradlew shared:generateBuildKonfig
    #  env:
    #    GITHUB_USER: ${{ github.actor }}
    #    GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache Pods
      uses: actions/cache@v3
      id: cache-pods
      with:
        path: './iosHyperskillApp/Pods'
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Install Pods if needed
      if: steps.cache-pods.outputs.cache-hit != 'true'
      working-directory: './iosHyperskillApp'
      run: bundle exec pod install --repo-update
    - name: Generate Google Cloud Storage code signing certificates keys file
      working-directory: './iosHyperskillApp'
      run: echo "$GOOGLE_CLOUD_STORAGE_CODE_SIGNING_CERTIFICATES_KEY_CONTENT" | base64 --decode > gc_keys.json
      env:
        GOOGLE_CLOUD_STORAGE_CODE_SIGNING_CERTIFICATES_KEY_CONTENT: ${{ secrets.GOOGLE_CLOUD_STORAGE_CODE_SIGNING_CERTIFICATES_KEY_CONTENT }}
    - name: Submit a new Beta Build to Firebase
      working-directory: './iosHyperskillApp'
      run: bundle exec fastlane beta
      env:
        KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
