name: iOS Beta Deployment

on:
  push:
    branches:
    - "feature/**" # TODO: Replace with release branch name

defaults:
  run:
    shell: bash
    
jobs:
  deployment:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Homebrew install git-crypt
      run: brew install git-crypt
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: TRUE
    - name: git-crypt unlock secrets
      run: |
        echo "$GIT_CRYPT_KEY" | base64 --decode > git-crypt.key
        git-crypt unlock git-crypt.key
        rm git-crypt.key
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.2
    - name: Execute Gradle build
      run: ./gradlew shared:generateBuildKonfig shared:allTests
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
