name: Labeler

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@4.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"