name: Feature Branch SwiftLint

on:
  push:
    branches:
      - 'feature/*'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --config iosHyperskillApp/.swiftlint.yml --path iosHyperskillApp/iosHyperskillApp/Sources --strict